### ISSUE TITLE
script for running the code

### ISSUE THREAD

**Issue by gmzang** [sxyu/pixel-nerf#1]
Nice work! and thanks for sharing the code.

Will you show any demo/ script to run the code for the scene shown in the paper later?  
Thanks!

**Comment by kajalsanklecha** [comment]
If not a script, even steps on how to run the code will suffice.

**Comment by vishnukool** [comment]
Agreed, the excitement is killing us.

**Comment by sxyu** [comment]
Thank you very much for all your interest! Sorry for procrastinating on finishing the code release. I am a bit overwhelmed by all this interest as this is my first research project.

We will most likely get this in before the end of the break (3 weeks). If you can't wait, please email me and I can provide some private code for now, by early next week, but likely not every experiment will be in.

I will keep this issue open until all that is done.

**Comment by anilesec** [comment]
Dear Alex,

Thanks for your kind gesture to provide the private code. How would I contact you? 

Thank you!
Anil

**Comment by ghost** [comment]
@sxyu can you please also provide a google colab for inference thanks

**Comment by sxyu** [comment]
I apologize if I couldn't respond to all of your emails :(.  In the end, I decided to simply release updated code to *this public* repository.
@ak9250 I will look into that, at least for real object experiment that's a good idea

**Comment by ghost** [comment]
@sxyu any update on this?
