### ISSUE TITLE
One question about cv2.decomposeProjectionMatrix

### ISSUE THREAD

**Issue by pengsongyou** [sxyu/pixel-nerf#10]
Hi Alex,

First of all, congrats on the great work! 

I was playing around with your code on DTU dataset a bit, and encountered one question, which might be a bit dumb:

In [this line](https://github.com/sxyu/pixel-nerf/blob/f1e24a720c0999715a6d02f1ec523972b6a8b744/src/data/DVRDataset.py#L163), you use `cv2.decomposeProjectionMatrix(P)` to obtain the `K`, `R` and `t` from the projection matrix `P`. However, when I tried to compose these components back via `K @ np.concatenate((R, t[:3]/t[3]), axis=1) `, I could not obtain `P` back. After playing around with it a bit, I realize that the translation part is not supposed to be `t[:3]/t[3]`, but `-R@(t[:3]/t[3])`, and we can get the projection matrix back. However, in your implementation, you are using `t[:3]/t[3]` for all the rest. I am wondering how could this not lead to issue, since the [`gen_rays`](https://github.com/sxyu/pixel-nerf/blob/2929708e90b246dbd0329ce2a128ef381bd8c25d/src/util/util.py#L238) function takes in camera poses as the input.

Many thanks for your answers in advance!

Best,
Songyou

**Comment by phongnhhn92** [comment]
I have similar issue with you @pengsongyou. However, I am curious on the scale_matrix that @sxyu have used to scale the projection matrix. I wonder how to obtain those scale_matrix parameters?

**Comment by jingwang97** [comment]
I also curious on the scale_matrix,i used to think scale_matrix[:3,3] is avg camera center,but it is not,do you have any idea now?@phongnhhn92

**Comment by phongnhhn92** [comment]
![image](https://user-images.githubusercontent.com/11288381/110456469-47249780-80d2-11eb-9e5a-2dd6a737bedb.png)
@jingwang97 I think the answer for your question is here. The author did not use the original DTU dataset, instead they used the dataset from the [DVR](https://github.com/autonomousvision/differentiable_volumetric_rendering) method. That explains the scaling of 1/300 here.

**Comment by sxyu** [comment]
Thank you for your questions.

> After playing around with it a bit, I realize that the translation part is not supposed to be t[:3]/t[3], but -R@(t[:3]/t[3])

Note the camera rotation R from OpenCV is w2c (world-to-camera), but t is c2w. In our code we use c2w convention.
Therefore our c2w pose matrix is formed as `pose = [R^t, t]`. You can recover the original projection matrix as: `K @ np.linalg.inv(pose)[:3]`

About scale: The scale and translation are a bit arbitrary. Sorry about this strangeness. I believe I simply scaled by 1/300 to a reasonable numerical range. The DTU from DVR only contained a small subset; we are only re-using their format.
