### ISSUE TITLE
Question about ResidualBlock

### ISSUE THREAD

**Issue by versatran01** [sxyu/pixel-nerf#12]
https://github.com/sxyu/pixel-nerf/blob/ddddb6b8f9dd29972305597c2d8ce31ededa82eb/src/model/resnetfc.py#L55

It seems like you are doing relu -> conv -> relu -> conv + res for the residual block, which is different from the original one, but more like the identity mapping one.
Could you provide some insights as to why (does the original resblock not work well?) Also why no batchnorm?

**Comment by sxyu** [comment]
Hi, first of all, this architecture was taken from DVR, so the design decisions are from them.

Please do note that this is a MLP resnet, so these are fully-connected layers (you could say 1x1 conv) not really conv as you might be thinking. Also, the architecture was adapted to feed in the image feature at the beginning of each resblock.
