### ISSUE TITLE
Error reading DTU dataset in train/train.py 

### ISSUE THREAD

**Issue by avani17101** [sxyu/pixel-nerf#13]
On running
`python train/train.py -n dtu_exp -c conf/exp/dtu.conf -D data/rs_dtu_4 -V 3 --gpu_id=0 --resume`
on[ DTU dataset](https://drive.google.com/drive/folders/1PsT3uKwqHHD2bEEHkIXB99AlIjtmrEiR)
I get the following error.

> EXPERIMENT NAME: dtu_exp
> CONTINUE? yes
> * Config file: conf/exp/dtu.conf
> * Dataset format: dvr_dtu
> * Dataset location: data/rs_dtu_4
> Loading DVR dataset data/rs_dtu_4 stage train 0 objs type: dtu
> Loading DVR dataset data/rs_dtu_4 stage val 0 objs type: dtu
> Loading DVR dataset data/rs_dtu_4 stage test 0 objs type: dtu
> dset z_near 0.1, z_far 5.0, lindisp False
> Using torchvision resnet34 encoder
> train dir data  <data.data_util.ColorJitterDataset object at 0x1471c5566e80>
> Traceback (most recent call last):
>   File "train/train.py", line 344, in <module>
>     trainer = PixelNeRFTrainer()
>   File "train/train.py", line 83, in __init__
>     super().__init__(net, dset, val_dset, args, conf["train"], device=device)
>   File "/ssd_scratch/cvit/avani.gupta/pixel-nerf/train/trainlib/trainer.py", line 17, in __init__
>     self.train_data_loader = torch.utils.data.DataLoader(
>   File "/home/avani.gupta/anaconda3/envs/pixelnerf/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 224, in __init__
>     sampler = RandomSampler(dataset, generator=generator)
>   File "/home/avani.gupta/anaconda3/envs/pixelnerf/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 95, in __init__
>     raise ValueError("num_samples should be a positive integer "
> ValueError: num_samples should be a positive integer value, but got num_samples=0

Can you clarify it the structure of rf_dtu_4 folder, it is rf_dtu_4/DTU/<data files>
<datafiles> has .lst and scan folders/
If this is correct, can you point out what is possibly causing this error?

**Comment by avani17101** [comment]
seem the error was due to no path given after --resume. Resolved

**Comment by lastapple** [comment]
I met the same error, how did you solve? I don't understand...... "no path given after --resume"? what path?

**Comment by Twizwei** [comment]
Hi @avani17101, could you please elaborate a little bit how to add a path? I met the same issue when I tried ShapeNet multi_obj, but I feel we can't add path after --resume, right? Thank!
