### ISSUE TITLE
Question related to input 3D coordinates

### ISSUE THREAD

**Issue by phongnhhn92** [sxyu/pixel-nerf#14]
Hi guys, I have a quick question.
In the DTU dataloader, after the transformation [step](https://github.com/sxyu/pixel-nerf/blob/ddddb6b8f9dd29972305597c2d8ce31ededa82eb/src/data/DVRDataset.py#L204), the output pose is in camera or world space (cam-to-world or world-to-cam) ? 

I am also a bit confused [here](https://github.com/sxyu/pixel-nerf/blob/ddddb6b8f9dd29972305597c2d8ce31ededa82eb/src/model/models.py#L182) as well. It seems like the sampled 3D points are transformed to the camera space of input views. The coordinates  xyz of these points are then feed to the MLP. I thought the input 3D coordinates to the MLP should be points in the world space just like NERF paper. Can you clarify this ?

**Comment by sxyu** [comment]
- In dataloader the pose is c2w.
- This is because we want to input point positions in **viewer-centric space**. This transformation of points from world to camera space makes the network invariant to choice of coordinate system (at least up to rotations).
