### ISSUE TITLE
Question about training category-specific

### ISSUE THREAD

**Issue by primecai** [sxyu/pixel-nerf#21]
Hello,

Great work and thanks for releasing the code!
I'm a bit confused about the training process, in the paper it is mentioned as "A single model is trained for each object class with 50 random views per object instance, randomly sampling either one or two of the training views to encode", I understand this as you firstly use 50 views per object instance to train the general categorical representation, and for the actual training scene, you use only 1-2 views? I think I didn't quite get this process, some further elaboration will be very helpful.

Many thanks.

**Comment by RoniPaiss** [comment]
As I understand it, they use 50 target views and 1-2 source views which they encode and feed to the network

**Comment by primecai** [comment]
Do you mind elabrating more on this? How many views per object instance are they using to train the model?

Thanks in advance.

**Comment by sxyu** [comment]
Yes 50 views per instance are used in total. 1-2 views are encoded each time, while all 50 views are used for supervision

**Comment by dwangxxx** [comment]
> Yes 50 views per instance are used in total. 1-2 views are encoded each time, while all 50 views are used for supervision

Hello, I have a question about training views. In this paper, you mentioned that you can train this model with only 3 views. But in the source code,  you choice 3 views randomly. This means that the whole views of a scene are applied for training. I can't understand this, would you like to provide me some details?

**Comment by chensjtu** [comment]
I have the same question with @dwangxxx
