### ISSUE TITLE
Question about coordinate system of SRNDataset, DVRDataset

### ISSUE THREAD

**Issue by xingyi-li** [sxyu/pixel-nerf#23]
Hi, @sxyu, congrats on your great work in CVPR 2021!

When I am reading your code, I notice that in the SRNDataset and DVRDataset, there is a coordinate transform step.
Specifically, for DTU in DVRDataset, you do:
```
if sub_format == "dtu":
    self._coord_trans_world = torch.tensor(
        [[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]],
        dtype=torch.float32,
    )
    self._coord_trans_cam = torch.tensor(
        [[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]],
        dtype=torch.float32,
    )

pose = (
                self._coord_trans_world
                @ torch.tensor(pose, dtype=torch.float32)
                @ self._coord_trans_cam
            )
```
for NMR in DVRDataset, you do:
```
else:
    self._coord_trans_world = torch.tensor(
        [[1, 0, 0, 0], [0, 0, -1, 0], [0, 1, 0, 0], [0, 0, 0, 1]],
        dtype=torch.float32,
    )
    self._coord_trans_cam = torch.tensor(
        [[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]],
        dtype=torch.float32,
    )
pose = (
                self._coord_trans_world
                @ torch.tensor(pose, dtype=torch.float32)
                @ self._coord_trans_cam
            )
```
However, for SRN dataset in SRNDataset, you do:
```
self._coord_trans = torch.diag(
            torch.tensor([1, -1, -1, 1], dtype=torch.float32)
        )
pose = pose @ self._coord_trans
```
First, I understand that your camera coordinate system is x right, y up, z out (to my knowledge, this is the OpenGL style coordinate system). Then for DVR, they use the OpenCV system, where x right, y down, z in. Also, I have checked [SRN](https://github.com/vsitzmann/scene-representation-networks#coordinate-and-camera-parameter-conventions), they use the OpenCV style camera coordinate system as well.

Second, after seeing #2, I also understand the reason why there is a coordinate transform step. Because you want to utilize the Rt matrix where OpenCV coordinate system is used, to transform ``cam_unproj_map`` to the world space, you have to first transform ``cam_unproj_map`` from OpenGL style into OpenCV style by timing ``self._coord_trans_cam``, then you do old camera2world transform ``pose``, finally you time ``self._coord_trans_world`` to transform back to OpenGL style system. This is something that I can understand. (Also refer to [stackoverflow link](https://stackoverflow.com/questions/1263072/changing-a-matrix-from-right-handed-to-left-handed-coordinate-system))

However, here are some questions:
1. Why do you do ``pose = pose @ self._coord_trans`` in SRNDataset, while ``self._coord_trans_world @ torch.tensor(pose, dtype=torch.float32) @ self._coord_trans_cam`` in DVRDataset?
2. Why do you use different ``self._coord_trans_world`` and ``self._coord_trans_cam`` in DVRDataset?
4. Is there any mistake in the above? Please point it out, thanks~

Best,
Xingyi Li

**Comment by sxyu** [comment]
You are correct. The point of multiplying by diag(1, -1, -1, 1) in SRN dataset is to convert point in OpenGL-style camera space to OpenCV camera space.
 
The `coord_trans_world` is fairly unnecessary. At some point, I just wanted to standardize the world coordinate system to z-up, but this should not matter.

All coordinate systems should be right-handed.
