### ISSUE TITLE
How to calculate camera matrix in pose folder for custom data ?

### ISSUE THREAD

**Issue by vishnukool** [sxyu/pixel-nerf#3]
Hi, 
This might be a trivial question. But I'm trying to figure out how to generate what looks like a camera matrix in pose.txt
Say I have 2 images like below from internet. I know what the camera angles are θ and Φ (Spherical coordinate system). From there how do I generate the matrix in pose folder for each ?
![videot0001_v000_view](https://user-images.githubusercontent.com/857006/103834432-3c994380-5038-11eb-866c-d62c1fa4b366.jpg)
![000000](https://user-images.githubusercontent.com/857006/103834566-9d288080-5038-11eb-9a03-a25b6957dd52.png)

**Comment by sxyu** [comment]
So it sounds like you want to use the SRN format. You can consult:
<https://github.com/vsitzmann/scene-representation-networks>

Each pose file is the 4x4 camera->world transform in row-major order, with camera space in OpenCV convention.
So for example you can let image 2 be "identity" and image 1 be the rotation from 1 to 2 (still OpenCV convention), which you can figure out from spherical coords (assuming 0 roll, you can compose 2 rotations).
Note that for internet photos, you would also need intrinsics, which might be a problem. It's a limitation of this deprojection-based method.

**Comment by Pranav-Saxena** [comment]
we can directly use the default dataloader after doing this step? or do we have to make changes to the dataloader as well?
