### ISSUE TITLE
dataset_type or dataset_format? 

### ISSUE THREAD

**Issue by anilesec** [sxyu/pixel-nerf#5]
Hi @sxyu 

How are different dataset classified into types or format? one difference could be they are all different datasets. Are there any criteria for a dataset to be categorized to specific data_type or format?

I would like to use this code or custom dataset and could you help to set this type of dataset? Should I have to convert the custom data into one of the data_types(srn, multi_obj, dvr)?

Thanks in Advance!

Best regards
Anil

**Comment by dwangxxx** [comment]
> Hi @sxyu
> 
> How are different dataset classified into types or format? one difference could be they are all different datasets. Are there any criteria for a dataset to be categorized to specific data_type or format?
> 
> I would like to use this code or custom dataset and could you help to set this type of dataset? Should I have to convert the custom data into one of the data_types(srn, multi_obj, dvr)?
> 
> Thanks in Advance!
> 
> Best regards
> Anil

Hi, I have the same question. Have you solved it?
