### ISSUE TITLE
Neural Volumes TV regularizer

### ISSUE THREAD

**Issue by sagniklp** [sxyu/pixel-nerf#8]
The following comment is unclear to me:
https://github.com/sxyu/pixel-nerf/blob/ddddb6b8f9dd29972305597c2d8ce31ededa82eb/src/render/nerf.py#L228

From my understanding of the code, I don't see the TV regularizer from the neural volumes paper around this comment. Is the regularizer used in pixelNeRF? Where is it implemented? Thanks!

**Comment by sxyu** [comment]
Sorry about the comment, I will remove it. We actually tried a bunch of other stuff but it was removed from the final code.
