### ISSUE TITLE
Results for `srn64_unseen` is weird

### ISSUE THREAD

**Issue by ThisIsIsaac** [sxyu/pixel-nerf#9]
https://user-images.githubusercontent.com/49523965/104848234-5d5e7480-5927-11eb-8d8a-fb8af3829acf.mp4

when run with: 
`python eval/gen_video.py --name sn64_unseen -D /data/private/pixel_nerf_data/NMR_Dataset --gpu_id 0 --split test -P 2 -S 0`

**Comment by ThisIsIsaac** [comment]
Resolved.

**Comment by dwangxxx** [comment]
> Resolved.

Hi, I have the same question in DTU dataset. How do you resolve this problem?

**Comment by ThisIsIsaac** [comment]
@dwangxxx try adding argument `--spheric_poses`

**Comment by dwangxxx** [comment]
> @dwangxxx try adding argument `--spheric_poses`
It doesn't work. Unrecognized arguments. Do you test the DTU dataset successfully?

**Comment by dwangxxx** [comment]
> @dwangxxx try adding argument `--spheric_poses`

It doesn't work. Unrecognized arguments. Do you test the DTU dataset successfully?
